directory: "Developer" # Starts at $HOME, so this would resolve to ~/Developer/
title: "Projects" # default: "Hop"
icons: "true" # default: false
editor: "nvim" # default: "code" 
include_files: "false" # default: false
